### ISSUE TITLE
Building of version 1.4 is not completed

### ISSUE THREAD

**Issue by DrDaveD** [cvmfs-contrib/cvmfs-contrib-release#3]
Copied from a comment in #2 after the PR was merged:

I see the 1.4-1 rpms, but the .deb although it has a timestamp of today still says it is 0.1.0. Can you please fix that? Also please update cvmfs-contrib-release-latest.rpm to point to the 1.4-1 rpm.

Also please add the v1.4 tag on the github repo.

**Comment by DrDaveD** [comment]
@jblomer This is for you.  I thought I would be able to assign it to you but I can't.

**Comment by jblomer** [comment]
@DrDaveD As for the debian version number, the changelog file indicates that the version number should be updated automatically. I think you'd need to take a look, I can build again after the next PR.

**Comment by DrDaveD** [comment]
Ah so do you build using ci/build_package.sh and I should update the version there similar to the way cvmfs does?

**Comment by DrDaveD** [comment]
See pr #5

**Comment by jblomer** [comment]
Thanks!  So we have

- new builds with version 1.4 for the Debian package
- updated "latest" symlinks
- The v1.4 tag

**Comment by DrDaveD** [comment]
Very good, thank you.
